{{- if or .Values.templates (not .Values.config.asSecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "calert.fullname" . }}-config
  labels:
{{ include "calert.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- if not .Values.config.asSecret }}
  config.toml: |
    {{- include "calert.configToml" . | nindent 4 }}
  {{- end }}
{{- end }}
