{{- if and .Values.config.asSecret (not .Values.config.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "calert.fullname" . }}-config
  labels:
{{ include "calert.labels" . | indent 4 }}
type: Opaque
data:
  config.toml: {{ include "calert.configToml" . | b64enc | quote }}
{{- end }}
